### ISSUE TITLE
No module named ddcci_plasmoid_backend

### ISSUE THREAD

**Issue by QazCetelic** [davidhi7/ddcci-plasmoid#22]
![image](https://user-images.githubusercontent.com/51381523/235321078-288bd52c-ebf5-4af2-b4de-3b398dd15229.png)

**Comment by KOT040188** [comment]
I have the same problem. I changed the name to ddcci-plasmoid-backend, but that didn't help.
`kot@192:~$ python3 -m ddcci-plasmoid-backend
/usr/bin/python3: No module named ddcci-plasmoid-backend
`
`kot@192:~$ pipx install ddcci-plasmoid-backend
pipx version is 1.4.0
Default python interpreter is '/usr/bin/python3.11'
Determined package name: ddcci-plasmoid-backend
Package name determined in 0.0s
running <checking pip's availability>
Time since last upgrade of shared libs, in seconds: 559. Upgrade will be run by pipx if greater than 2592000.
running <checking pip's availability>
'ddcci-plasmoid-backend' already seems to be installed. Not modifying existing installation in
'/home/kot/.local/share/pipx/venvs/ddcci-plasmoid-backend'. Pass '--force' to force installation.
`

**Comment by davidhi7** [comment]
See the README: ```
Note: If you used pipx to install the backend in the previous step, the widget setting Backend executable command should be ~/.local/bin/ddcci_plasmoid_backend (which is the default installation path of pipx).```

**Comment by KOT040188** [comment]
> See the README:
> 
> > Note: If you used pipx to install the backend in the previous step, the widget setting Backend executable command should be ~/.local/bin/ddcci_plasmoid_backend (which is the default installation path of pipx).

It does not help! Widget still doesn't work!
`kot@192:~$ pipx install ddcci_plasmoid_backend pipx version is 1.4.0 Default python interpreter is '/usr/bin/python3.11' Determined package name: ddcci-plasmoid-backend Package name determined in 0.0s running <checking pip's availability> Time since last upgrade of shared libs, in seconds: 88825. Upgrade will be run by pipx if greater than 2592000. running <checking pip's availability> 'ddcci-plasmoid-backend' already seems to be installed. Not modifying existing installation in '/home/kot/.local/share/pipx/venvs/ddcci-plasmoid-backend'. Pass '--force' to force installation.`

**Comment by davidhi7** [comment]
I don't see anything wrong with this, the backend appears to be installed correctly. Try to run `~/.local/bin/ddcci_plasmoid_backend` manually to see if it works.

**Comment by QazCetelic** [comment]
> Not modifying existing installation in '/home/kot/.local/share/pipx/venvs/ddcci-plasmoid-backend'.

Maybe `/home/kot/.local/share/pipx/venvs/ddcci-plasmoid-backend` isn't added to path. @KOT040188 have you tried changing the "Backend executeable command" in the widget config to `python3 /home/kot/.local/share/pipx/venvs/ddcci-plasmoid-backend`?

**Comment by KOT040188** [comment]
> ~/.local/bin/ddcci_plasmoid_backend

Yes, it's in place.


> python3 /home/kot/.local/share/pipx/venvs/ddcci-plasmoid-backend

```
kot@192:~$ python3 /home/kot/.local/share/pipx/venvs/ddcci-plasmoid-backend
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/lib64/python3.11/site-packages/PIL/__main__.py", line 1, in <module>
    from .features import pilinfo
ImportError: attempted relative import with no known parent package

```

**Comment by KOT040188** [comment]
Any thoughts?

**Comment by davidhi7** [comment]
I still don't think I understood your issue.

You should be able able to run `/home/kot/.local/bin/ddcci_plasmoid_backend` to invoke the backend. There is be no need to deal with any internal pipx directories and executables. Please try to execute `/home/kot/.local/bin/ddcci_plasmoid_backend` directly and post the output.

In your last replies you tried to pass `/home/kot/.local/bin/ddcci_plasmoid_backend` and other files  as an argument to python. While the code is of course written in python, it can't be executed by python directly without further steps. Instead you must execute the file as an executable, so without putting `python3` in front of the file name.

**Comment by KOT040188** [comment]
`kot@192:~$ /home/kot/.local/bin/ddcci_plasmoid_backend
usage: plasma-ddcci-backend [-h] [-d] [--debug-log LOG_FILE] {version,detect,set-brightness} ...
plasma-ddcci-backend: error: the following arguments are required: command
`

**Comment by davidhi7** [comment]
Looks like it's working as intented, `home/kot/.local/bin/ddcci_plasmoid_backend detect` should now output connected monitors, encoded in JSON. Now you need to right-click the widget, open the settings and set the `Backend executable command` to `home/kot/.local/bin/ddcci_plasmoid_backend`.

**Comment by davidhi7** [comment]
Please post the error message then.

**Comment by KOT040188** [comment]
https://imgur.com/a/7QJuoGk

**Comment by KOT040188** [comment]
Writes that there is no such file or directory

**Comment by KOT040188** [comment]
Finally the widget is working. Thank you.

**Comment by KOT040188** [comment]
This means that the default command in the widget settings was incorrect. Something needs to be done about this.

**Comment by davidhi7** [comment]
> This means that the default command in the widget settings was incorrect. Something needs to be done about this.

It is correct assuming one installed the widget using the default installation method, that is using pip. If pipx is used, like in your case, the command must be changed but this is documented: 

> Note: If you used pipx to install the backend in the previous step, the widget setting Backend executable command should be ~/.local/bin/ddcci_plasmoid_backend (which is the default installation path of pipx).

That being said, installing with pipx is going to be the default recommendation in a future release.

**Comment by noyannus** [comment]
Installing with `pipx install ddcci_plasmoid_backend` _as user instead of as root_ made all the difference for me. (Now that I have monitor that's actually `ddcci`-capable. :-) )
