### ISSUE TITLE
pip unable to install due to externally managed environment

### ISSUE THREAD

**Issue by neomoth** [davidhi7/ddcci-plasmoid#38]
Attempting to run `pip install ddcci-plasmoid-backend`, this error comes up:
```
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try 'pacman -S
    python-xyz', where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Arch-packaged Python package,
    create a virtual environment using 'python -m venv path/to/venv'.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip.
    
    If you wish to install a non-Arch packaged Python application,
    it may be easiest to use 'pipx install xyz', which will manage a
    virtual environment for you. Make sure you have python-pipx
    installed via pacman.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```
I am aware that i can pass `--break-system-packages` but I am unsure if this package has the potential to break anything managed by pacman/yay on my system, or break python in the process. Is this package safe to install via pip, or should I work on getting this installed by pacman somehow despite the fact that a pacman equivalent does not exist

**Comment by davidhi7** [comment]
There is no pacman/AUR package for this yet, the only way to install the backend involves the python package repository. Installing it globally using pip is in fact a bad idea because it can break system packages (although this is highly unlikely for this package specifically). The better alternative is using pipx to install the backend in a virtual environment, so it can't interfere with system packages.

To do so, install `python-pipx` from the Arch repositories, run `pipx install ddcci_plasmoid_backend` and set the `Backend executable command` in the widget settings to `~/.local/bin/ddcci_plasmoid_backend`. This will also be the default recommended installation method in the next release.

**Comment by neomoth** [comment]
sweet, thanks
