### ISSUE TITLE
Version tag in plasmoid/metadata.json is out of date

### ISSUE THREAD

**Issue by peterhoeg** [davidhi7/ddcci-plasmoid#57]
It might make sense to generate this file instead of manually maintaining and then injecting the version then.

**Comment by davidhi7** [comment]
Technically the version tag is not out of date, the versioning scheme is just bad.  Ever since publishing the first version, I have been unsure whether to use the same or a different version tag for both the backend or the frontend. Using the same tag for both would lead to many new backend/widget versions published at pypi/kde store with no actual changes, whereas using different version tags would be unnecessarily  complex for this little code base. Until now I have opted to choose probably a bad compromise of both, using a common version tag for both (currently 0.1.10) but only incrementing the version in the corresponding package metadata file and only publishing a new version if there were actually any changes to the package. And since the last few patches only affected the backend, the plasmoid version tag is still stuck to 0.1.8.

Now I plan to change this versioning scheme to something meaningful, but have procrastinated this for now.

**Comment by davidhi7** [comment]
In the process of merging Plasma 6 support I also just updated the metadata.json version tag, manually for now. Automating this is something I should definitely consider, but is not really urgent since currently not a lot of development happens.
